# Generated by Django 3.1.3 on 2020-12-08 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('age_y', models.IntegerField(blank=True, null=True)),
                ('age_m', models.IntegerField(blank=True, default=0, null=True)),
                ('age_d', models.IntegerField(blank=True, default=0, null=True)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=100)),
                ('cc', models.CharField(blank=True, max_length=300, null=True)),
                ('oe', models.CharField(blank=True, max_length=300, null=True)),
                ('pulse', models.CharField(blank=True, max_length=50, null=True)),
                ('bp', models.CharField(blank=True, max_length=50, null=True)),
                ('others_test', models.CharField(blank=True, max_length=400, null=True)),
                ('date', models.DateField(default='2020-12-08')),
                ('status', models.BooleanField(default=False)),
                ('test', models.ManyToManyField(blank=True, to='prescription.Test')),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_result', models.TextField(blank=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('next_visit', models.IntegerField(blank=True, default=0, null=True)),
                ('diagonosis', models.CharField(blank=True, max_length=200, null=True)),
                ('advice', models.CharField(blank=True, max_length=200, null=True)),
                ('med1', models.CharField(blank=True, max_length=200, null=True)),
                ('rule1', models.CharField(blank=True, max_length=200, null=True)),
                ('med2', models.CharField(blank=True, max_length=200, null=True)),
                ('rule2', models.CharField(blank=True, max_length=200, null=True)),
                ('med3', models.CharField(blank=True, max_length=200, null=True)),
                ('rule3', models.CharField(blank=True, max_length=200, null=True)),
                ('med4', models.CharField(blank=True, max_length=200, null=True)),
                ('rule4', models.CharField(blank=True, max_length=200, null=True)),
                ('med5', models.CharField(blank=True, max_length=200, null=True)),
                ('rule5', models.CharField(blank=True, max_length=200, null=True)),
                ('med6', models.CharField(blank=True, max_length=200, null=True)),
                ('rule6', models.CharField(blank=True, max_length=200, null=True)),
                ('med7', models.CharField(blank=True, max_length=200, null=True)),
                ('rule7', models.CharField(blank=True, max_length=200, null=True)),
                ('med8', models.CharField(blank=True, max_length=200, null=True)),
                ('rule8', models.CharField(blank=True, max_length=200, null=True)),
                ('med9', models.CharField(blank=True, max_length=200, null=True)),
                ('rule9', models.CharField(blank=True, max_length=200, null=True)),
                ('med10', models.CharField(blank=True, max_length=200, null=True)),
                ('rule10', models.CharField(blank=True, max_length=200, null=True)),
                ('patientname', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='prescription.patient')),
            ],
        ),
    ]
